### ISSUE TITLE
"npm run build" command is failed

### ISSUE THREAD

**Issue by kkeeth** [black-trooper/semantic-ui-riot#23]
I tried the build with the following steps, but it failed.

```bash
$ git clone 
$ npm install
$ npm run build
```

`npm run test` is failed, because `TOTAL: 5 FAILED, 193 SUCCESS`.
So, `npm run dev` and `npm run prod` were not executed.

Therefore, I skipped `npm run test` and tried the build.

```diff
-    "build": "npm run compile && npm run test && npm run dev && npm run prod"
+    "build": "npm run compile && npm run dev && npm run prod"
```

But, one error occurred too...

```
'date-fns' is imported by tags/datepicker/su-datepicker.riot, but could not be resolved – treating it as an external dependency
```

So, please check 🙇 Thanks!

**Comment by black-trooper** [comment]
I commented out because it was a test that did not affect much.
adf28c6a46ee746b3604a587ef10ddd67255c8a0

**Comment by kkeeth** [comment]
ok. Once, I close this issue ticket.
